name: Build APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Create Flutter project
        run: flutter create .

      - name: Copy main Dart file
        run: cp main_kalkulator_tpt_kirmir_FIX_GALIAN_*.dart lib/main.dart

      - name: Get dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release
